runtime: python

runtime_config:
  python_version: 3.7
env: flex
entrypoint: gunicorn -b :$PORT main:app --timeout 90
manual_scaling:
  instances: 1
beta_settings:
  cloud_sql_instances: erudite-bonbon-352111:asia-southeast2:pamjaya-db
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20

env_variables:
  ENV: PROD
  FLASK_APP: main.py
  DB_HOST: 34.101.149.127
  DB_DATABASE: pamjayadb
  DB_USERNAME: root
  DB_PASSWORD: pamjaya123
  PROJECT_ID: erudite-bonbon-352111
  INSTANCE_NAME: pamjaya-db
  TWILIO_ACCOUNT_SID:
  TWILIO_AUTH_TOKEN:
  VERIFICATION_SID:
